[package]
name = "pylon-lfp-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-io.workspace = true
log = "0.4.28"
zerocopy = { version = "0.8.27", features = ["derive"] }

[dev-dependencies]
embedded-io = { version = "0.7.1", features = ["std"] }
simple_logger = "5.1.0"
